# Linear Algebra

In [1]:
import numpy as np

## 스칼라, 벡터, 매트릭스
#### Scaler(스칼라)
> 단순 숫자를 의미합니다. _e.g. 1,2,4.5_

#### Vector(벡터)
> 숫자가 담긴 리스트를 의미합니다. _e.g.[1,0,2]_

$$ x = \begin{bmatrix} 1 \\ 0 \\ 2 \end{bmatrix} \in \mathbb{R}^3 $$

- $n \times 1$ 사이즈의 크기를 갖고 있습니다.
- 기본적으로 Column Vector이며 $x^T$(Transpose)를 하게 되면 Row Vector로 바뀝니다.

#### Matrix(매트릭스)
> 2차원으로 이루어진 숫자 리스트를 의미합니다. 

$$ x = \begin{bmatrix} 1 & 6 \\ 3 & 4 \\ 5 & 2 \end{bmatrix} \in \mathbb{R}^3 $$

- **사이즈** : **3 X 2 사이즈**이며, **3개의 행(row)과 2개의 열(column)** 으로 이루어져있습니다.
- 각각을 Column Vector, Row Vector라고 부릅니다.
- **컴포넌트(Component)** : $(i,j)$ 형식으로 **$i$ 는 행(Row)을 $j$는 열(Column)** 을 의미합니다.

### Vector 실습

In [2]:
# column vector
c = np.array([1,2,3])
print(c.shape)

# obtaining a particular entry
print (c[0])

(3,)
1


In [3]:
# row vector
r = np.array([ [1,2,3] ])
print (r.shape)

(1, 3)


In [4]:
# obtaining a particular entry
print (r[0,1])

2


### Matrix 실습

In [5]:
# creating a matrix with all zeros
a = np.zeros((2,2))
print (a)
# creating a matrix with all ones
b = np.ones((2,2))
print (b)
             
# creating a matrix filled with the same constant
c = np.full((2,2), 7)
print (c)
             
# creating a matrix with random values
d = np.random.random((2,2))
print (d)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7]
 [7 7]]
[[0.82634548 0.78383716]
 [0.02906112 0.22135154]]


In [6]:
# creating a matrix
A=np.array([[1,2],[3,4],[5,6]])
print (A)

# creating another matrix
B=np.array([[11,12,13,14],[15,16,17,18]])
B

[[1 2]
 [3 4]
 [5 6]]


array([[11, 12, 13, 14],
       [15, 16, 17, 18]])

In [7]:
# transpose a matrix
A.T

array([[1, 3, 5],
       [2, 4, 6]])

## 행렬의 덧셈, 곱셈
#### 덧셈
> 반드시 같은 사이즈이어야 합니다.
#### 스칼라 곱
> 상수배와 비슷한 의미를 가지고 있습니다.
#### 곱셈
> 스칼라로 변환하는 내적과 매트릭스로 변환하는 외적이 있습니다.

- 매트릭스 끼리 곱셈
$$ (3 \times 2)(2 \times 4) = (3 \times 4) $$

- 내적

$$ \begin{bmatrix} 3 & 2 & 1 \end{bmatrix} \begin{bmatrix} 1 \\ 3 \\ 5 \end{bmatrix} = \begin{bmatrix} 14 \end{bmatrix}  $$
- 외적

$$  \begin{bmatrix} 1 \\ 3 \\ 5 \end{bmatrix} \begin{bmatrix} 1 & 2 \end{bmatrix} = \begin{bmatrix} 1 & 2 \\ 3 & 6 \\ 5 & 10 \end{bmatrix}$$

> #### 📌  교환법칙(Commutative)는 성립하지 않습니다. $$ AB \ne BA $$
> 사이즈는 같으나 결과값이 달라질 수 있기 때문입니다.

> - 분배법칙(Distributive) : $ A(B+C) = AB + AC $
> - 결합법칙(Associative) : $ A(BC) = (AB)C $
> - Transpose : $ (AB)^T = B^TA^T $
> - 역행렬(Inverse) : $ (AB)^{-1} = B^{-1}A^{-1}$

### 매트릭스  곱셈 실습

In [8]:
# matrix-matrix multiplication
np.dot(A,B)

# matrix-matrix multiplication 
# size should match!
# np.dot(B,A)

array([[ 41,  44,  47,  50],
       [ 93, 100, 107, 114],
       [145, 156, 167, 178]])

# Linear System

## 선형 시스템
### Linear Equation(선형 방정식)
> 타겟 값 $b$와 상수(coefficients) $a_1, ... , a_n$으로 이루어진 식입니다.
$$ a_1x_1 + a_2x_2 + ... + a_nx_n = b $$

$$ a^Tx = b $$

- $a$를 Transpose 시켜 $x$와 내적한 방정식입니다.

### Linear System(선형 시스템)
> 선형 방정식의 집합을 의미합니다. 같은 변수가 여러개 있다는 뜻입니다.

- 만약 아래 데이터를,

|Person ID|Weight|Height|is_smoking|Life-Span|
|:--:|:--:|:--:|:--:|:--:|
|1|60|5.5|1|66|
|2|65|5.0|0|74|
|3|55|6.0|1|78|

- 선형 시스템으로 작성하면,
$$ 60x_1 + 5.5x_2 + 1x_3 = 66  \\  65x_1 + 5.0x_2 + 0x_3 = 74 \\  55x_1 + 6.0x_2 + 1x_3 =78  $$

- 여기서 세개의 식을 만족하는 최적의 계수($\x$)를 찾아야 합니다.
$$  \begin{bmatrix} 60 & 5.5  & 1 \\ 65 & 5.0  & 0 \\ 55 & 6.0  & 1  \end{bmatrix} \begin{bmatrix} x_1 \\ x_2 \\ x_3  \end{bmatrix} = \begin{bmatrix} 66 \\ 74 \\ 78  \end{bmatrix} $$

> 🤔 그렇다면 최적의 계수($x$)를 어떻게 찾을 수 있을까요?


### 선형 시스템 실습

In [9]:
# coefficient matrix A and a vector b
A=np.array([[60, 5.5, 1],[65, 5.0, 0],[55, 6.0, 1]])
b=np.array([66, 70, 78])

## 항등행렬과 역행렬
### Identity Matrix (항등행렬)
- **정사각형 매트릭스**로 대각선(diagonal)의 숫자(entries)가 1이며, 나머지가 숫자가 0인 행렬
- 어떤 벡터랑 곱해도 **자기 자신을 만들어내는 행렬**입니다.

$$ I_3 = \begin{bmatrix} 1&0&0 \\ 0&1&0 \\ 0&0&1  \end{bmatrix} $$

$$ I_nx = x $$

### Inverse Matrix (역행렬)
- **정사각형 매트릭스**로 직사각형 매트릭스에서는 교환법칙으로 항등행렬을 만들 수 없습니다.

$$ A^{-1} = \frac{1}{ad-bc}\begin{bmatrix} d&-b \\ -c&a  \end{bmatrix} $$

$$ A^{-1}A = I_n \quad AA^{-1} = I_n $$

### 항등행렬, 역행렬 실습

In [10]:
# identity matrix 
eye3 = np.eye(3)
eye3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
# computing an inverse
from numpy.linalg import inv
A_inv = inv(A)
A_inv

array([[ 0.08695652,  0.00869565, -0.08695652],
       [-1.13043478,  0.08695652,  1.13043478],
       [ 2.        , -1.        , -1.        ]])

## 역행렬로 선형 시스템 해결하기

$$ Ax = b \\ A^{-1}Ax = A^{-1} b \\ I_nx = A^{-1}b \\ x = A^{-1}b$$

- 각 항에 역행렬을 곱하여 항등행렬을 만들어 계산합니다.

> 만약 역행렬 2X2 사이즈 보다 큰 경우 **[🔗 가우시안 소거법(Gaussian elimination)]()** 을 사용합니다.

> 📌 **역행렬이 존재하지 않은 경우**, **$ad-bc = 0$인 상태**를 의미합니다. 
> 이러한 경우에는 **$\det A$** 라고 부릅니다.
> - 해가 무수히 많거나(여러해가 동일한 경우)
> - 해가 없는 상태(해가 나오지 않은 경우)

### 직사각형 매트릭스일 경우 선형 시스템 해결하기 
- **Rows > Columns** : 해가 없는 경우를 의미합니다.
- **Columns > Rows** : 정규화(Regularzation)이 필요한 상태로 해가 무수히 많은 경우를 의미합니다.

> 이러한 경우에는 머신러닝을 이용해 최적화로 근사값을 구하는 방법을 택합니다.

[🔗 Properites of determinants - Gilbert Strang](https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/resources/lecture-18-properties-of-determinants/) <br>
[🔗 Python Numpy Tutorial](https://cs231n.github.io/python-numpy-tutorial/) <br>
[🔗 딥러닝을 위한 선형대수 치트 시트 ](https://towardsdatascience.com/linear-algebra-cheat-sheet-for-deep-learning-cd67aba4526c) <br>

### 선행 시스템 해결 실습

In [12]:
# wrong matrix multiplication
A*A_inv

array([[ 5.21739130e+00,  4.78260870e-02, -8.69565217e-02],
       [-7.34782609e+01,  4.34782609e-01,  0.00000000e+00],
       [ 1.10000000e+02, -6.00000000e+00, -1.00000000e+00]])

In [13]:
# correct matrix multiplication
A.dot(A_inv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
# solution of a linear system
x=A_inv.dot(b)
x

array([ -0.43478261,  19.65217391, -16.        ])

In [16]:
# a better way to solve the same linear system
from numpy.linalg import solve
x = solve(A,b)
x

array([ -0.43478261,  19.65217391, -16.        ])